/**
 * Иконки Design v1: линейные, обводка 1.75px, скруглённые концы, без заливки.
 * Пути перенесены 1:1 из макетов — см. src/components/ui/Icon.tsx.
 */
export type IconName =
  | "activity"
  | "alert"
  | "arrow-right"
  | "brain"
  | "calendar"
  | "briefcase"
  | "check"
  | "check-circle"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "child"
  | "clock"
  | "close"
  | "dna"
  | "drop"
  | "eye"
  | "file-text"
  | "flask"
  | "heart"
  | "layers"
  | "list"
  | "menu"
  | "phone"
  | "pill"
  | "pin"
  | "plus"
  | "scan"
  | "search"
  | "shield"
  | "spinner"
  | "stethoscope"
  | "tooth"
  | "trash"
  | "user";
